name: fluent_ui_devtools_extension
description: "Dev Tools Extension for Fluent UI"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  devtools_app_shared: ^0.2.2
  devtools_extensions: ^0.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
